// Code generated by gommon from pkg/reporter/gommon.yml DO NOT EDIT.

package reporter

import dlog "github.com/dyweb/gommon/log"

func (c *Counter) SetLogger(logger *dlog.Logger) {
	c.log = logger
}

func (c *Counter) GetLogger() *dlog.Logger {
	return c.log
}

func (c *Counter) LoggerIdentity(justCallMe func() *dlog.Identity) *dlog.Identity {
	return justCallMe()
}

func (d *TSDB) SetLogger(logger *dlog.Logger) {
	d.log = logger
}

func (d *TSDB) GetLogger() *dlog.Logger {
	return d.log
}

func (d *TSDB) LoggerIdentity(justCallMe func() *dlog.Identity) *dlog.Identity {
	return justCallMe()
}
