language: go
sudo: true
services:
  - docker
git:
  depth: 3

# TODO: use docker service to start influxdb etc. and create database like oltpbench
# https://github.com/benchhub/oltpbench/blob/config/cleanup-v2/.travis.yml
go:
  - "1.13"
  - tip

# FIXME: enable test when we no longer rely on local go modules

install:
  - go version

script:
  - go version