package cmd

import (
	"fmt"

	"github.com/spf13/cobra"
)

var LoadCmd = &cobra.Command{
	Use:   "load",
	Short: "load generated data to tsdb",
	Long:  "load data generated by simulator into time series databases",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("lock and load")
	},
}
