// Code generated by gommon from pkg/runner/gommon.yml DO NOT EDIT.

package runner

import dlog "github.com/dyweb/gommon/log"

func (m *Manager) SetLogger(logger *dlog.Logger) {
	m.log = logger
}

func (m *Manager) GetLogger() *dlog.Logger {
	return m.log
}

func (m *Manager) LoggerIdentity(justCallMe func() *dlog.Identity) *dlog.Identity {
	return justCallMe()
}
